###전체 목록 조회
GET http://localhost:8080/api/guestbooks
Accept: application/json

###등록
POST http://localhost:8080/api/guestbooks
Content-Type: application/json

{
  "nickname": "test",
  "content": "hello"
}
###
POST http://localhost:8080/api/guestbooks
Content-Type: application/json

{
  "nickname": "guest",
  "content": "tester"
}